// Chinese translations
window.translations = {
    'common': {
        'welcome': '欢迎',
        'login': '登录',
        'logout': '登出',
        'register': '注册',
        'dashboard': '仪表板',
        'settings': '设置',
        'save': '保存',
        'cancel': '取消',
        'delete': '删除',
        'edit': '编辑',
        'search': '搜索',
        'loading': '加载中...',
        'error': '错误',
        'success': '成功',
        'confirm': '确认',
        'back': '返回',
        'next': '下一步',
        'finish': '完成',
        'submit': '提交',
        'reset': '重置',
        'close': '关闭',
        'open': '打开',
        'yes': '是',
        'no': '否',
        'ok': '确定',
        'name': '姓名',
        'email': '邮箱',
        'password': '密码',
        'phone': '电话',
        'address': '地址',
        'gender': '性别',
        'male': '男',
        'female': '女',
        'other': '其他',
        'prefer_not': '不愿透露',
        'date': '日期',
        'time': '时间',
        'status': '状态',
        'active': '活跃',
        'inactive': '不活跃',
        'pending': '待处理',
        'completed': '已完成',
        'failed': '失败',
        'info': '信息',
        'warning': '警告',
        'danger': '危险',
        'help': '帮助',
        'about': '关于',
        'contact': '联系',
        'privacy': '隐私政策',
        'terms': '服务条款',
        'language': '语言',
        'theme': '主题',
        'dark': '深色',
        'light': '浅色',
        'system': '系统',
        'version': '版本'
    },
    
    'auth': {
        'login_title': '欢迎回来',
        'login_subtitle': '登录以继续',
        'register_title': '创建账户',
        'register_subtitle': '开始您的旅程',
        'reset_title': '重置密码',
        'reset_subtitle': '输入您的邮箱以重置密码',
        'email_label': '邮箱',
        'password_label': '密码',
        'confirm_password': '确认密码',
        'forgot_password': '忘记密码？',
        'remember_me': '记住我',
        'no_account': '没有账户？',
        'has_account': '已有账户？',
        'sign_up': '注册',
        'sign_in': '登录',
        'sign_out': '登出',
        'reset_password': '重置密码',
        'send_reset_link': '发送重置链接',
        'reset_link_sent': '重置链接已发送到您的邮箱',
        'password_mismatch': '密码不匹配',
        'invalid_email': '请输入有效的邮箱地址',
        'invalid_password': '密码至少需要6个字符',
        'weak_password': '密码太弱',
        'medium_password': '中等强度密码',
        'strong_password': '强密码',
        'very_strong': '非常强的密码'
    },
    
    'dashboard': {
        'title': '仪表板',
        'welcome_back': '欢迎回来 {name}',
        'welcome_guest': '欢迎访客',
        'subtitle': '您项目的状态',
        'recent_projects': '最近项目',
        'ai_chat': 'AI聊天助手',
        'documentation': '文档',
        'coder': '代码编辑器',
        'projects_count': '您有 {count} 个进行中的项目',
        'files_count': '{count} 个文件',
        'lines_count': '{count} 行代码',
        'last_edited': '上次编辑 {time}',
        'created_at': '创建于 {time}',
        'start_chat': '开始聊天',
        'read_docs': '阅读文档',
        'open_coder': '打开代码编辑器',
        'continue_project': '继续编辑',
        'need_help': '需要帮助？与AI助手聊天',
        'learn_more': '了解更多'
    },
    
    'chat': {
        'title': 'AI聊天助手',
        'new_chat': '新聊天',
        'type_message': '输入消息...',
        'upload_file': '上传文件',
        'send': '发送',
        'thinking': 'AI正在思考...',
        'error': '抱歉，发生错误。请重试。',
        'history': '聊天历史',
        'clear_history': '清除历史',
        'delete_chat': '删除聊天',
        'chat_with_ai': '与AI助手聊天',
        'file_uploaded': '已上传文件: {filename}',
        'code_detected': '检测到代码。要在代码编辑器中打开吗？',
        'open_in_coder': '在代码编辑器中打开'
    },
    
    'coder': {
        'title': '代码编辑器',
        'new_file': '新建文件',
        'new_folder': '新建文件夹',
        'save': '保存',
        'save_all': '全部保存',
        'run': '运行',
        'preview': '预览',
        'terminal': '终端',
        'file_explorer': '文件浏览器',
        'file_name': '文件名',
        'file_type': '文件类型',
        'create_file': '创建文件',
        'delete_file': '删除文件',
        'rename_file': '重命名文件',
        'unsaved_changes': '有未保存的更改',
        'save_to_drive': '保存到Google云端硬盘',
        'load_from_drive': '从Google云端硬盘加载',
        'enter_file_name': '输入文件名（带扩展名）:',
        'select_language': '选择语言',
        'html': 'HTML',
        'css': 'CSS',
        'javascript': 'JavaScript',
        'python': 'Python',
        'json': 'JSON',
        'markdown': 'Markdown'
    },
    
    'terminal': {
        'title': '终端',
        'new_terminal': '新建终端',
        'clear_terminal': '清除终端',
        'copy': '复制',
        'paste': '粘贴',
        'command_not_found': '未找到命令: {command}',
        'file_not_found': '未找到文件: {file}',
        'directory_not_found': '未找到目录: {dir}',
        'welcome_message': '欢迎使用 amkyaw.dev 终端 v2.0.0',
        'help_message': '输入 \'help\' 查看可用命令'
    },
    
    'docs': {
        'title': '文档',
        'search': '搜索文档...',
        'categories': '分类',
        'all': '全部',
        'getting_started': '入门指南',
        'coder': '代码编辑器',
        'chat': 'AI聊天',
        'terminal': '终端',
        'api': 'API',
        'tutorials': '教程',
        'faq': '常见问题',
        'examples': '代码示例',
        'quick_start': '快速入门指南',
        'copy': '复制',
        'copied': '已复制！'
    },
    
    'about': {
        'title': '关于我们',
        'subtitle': '通过AI驱动工具赋能开发者',
        'mission': '我们的使命',
        'mission_text': '通过智能工具和AI辅助，让编程人人可及',
        'vision': '我们的愿景',
        'vision_text': '创造一个任何人都能通过代码实现想法的世界',
        'founder': '创始人兼首席开发者',
        'founder_name': '昂图雷',
        'stats_users': '活跃用户',
        'stats_projects': '创建的项目',
        'stats_conversations': 'AI对话',
        'stats_tutorials': '教程',
        'features': '为什么选择我们',
        'feature_ai': 'AI驱动',
        'feature_ai_desc': '获取智能代码建议和调试帮助',
        'feature_cloud': '云存储',
        'feature_cloud_desc': '通过Google云端硬盘保存和同步项目',
        'feature_multi_lang': '多语言支持',
        'feature_multi_lang_desc': '支持20多种编程语言',
        'feature_responsive': '响应式设计',
        'feature_responsive_desc': '在所有设备上获得完美体验',
        'contact': '联系我们',
        'email': '邮箱',
        'phone': '电话',
        'address': '地址',
        'address_details': '内比都, 缅甸',
        'copyright': '© {year} amkyaw.dev。保留所有权利。'
    },
    
    'admin': {
        'title': '管理面板',
        'subtitle': '管理您的平台和用户',
        'total_users': '总用户数',
        'active_users': '活跃用户',
        'total_projects': '总项目数',
        'total_chats': '总AI对话数',
        'recent_activity': '最近活动',
        'user_management': '用户管理',
        'system_status': '系统状态',
        'platform_settings': '平台设置'
    },
    
    'errors': {
        '404_title': '页面未找到',
        '404_message': '抱歉！您要找的页面不存在',
        '403_title': '访问被拒绝',
        '403_message': '您没有权限访问此页面',
        '500_title': '服务器错误',
        '500_message': '服务器发生错误。请稍后重试。',
        'back_home': '返回首页',
        'go_dashboard': '前往仪表板',
        'try_again': '重试',
        'search': '搜索...'
    }
};