// English translations - Complete
window.translations = {
    'common': {
        'welcome': 'Welcome',
        'login': 'Login',
        'logout': 'Logout',
        'register': 'Register',
        'dashboard': 'Dashboard',
        'settings': 'Settings',
        'save': 'Save',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'edit': 'Edit',
        'search': 'Search',
        'loading': 'Loading...',
        'error': 'Error',
        'success': 'Success',
        'confirm': 'Confirm',
        'back': 'Back',
        'next': 'Next',
        'finish': 'Finish',
        'submit': 'Submit',
        'reset': 'Reset',
        'close': 'Close',
        'open': 'Open',
        'yes': 'Yes',
        'no': 'No',
        'ok': 'OK',
        'name': 'Name',
        'email': 'Email',
        'password': 'Password',
        'phone': 'Phone',
        'address': 'Address',
        'gender': 'Gender',
        'male': 'Male',
        'female': 'Female',
        'other': 'Other',
        'prefer_not': 'Prefer not to say',
        'date': 'Date',
        'time': 'Time',
        'status': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'pending': 'Pending',
        'completed': 'Completed',
        'failed': 'Failed',
        'info': 'Information',
        'warning': 'Warning',
        'danger': 'Danger',
        'help': 'Help',
        'about': 'About',
        'contact': 'Contact',
        'privacy': 'Privacy Policy',
        'terms': 'Terms of Service',
        'language': 'Language',
        'theme': 'Theme',
        'dark': 'Dark',
        'light': 'Light',
        'system': 'System',
        'notifications': 'Notifications',
        'sound': 'Sound',
        'vibration': 'Vibration',
        'version': 'Version',
        'update': 'Update',
        'check_update': 'Check for Updates',
        'download': 'Download',
        'upload': 'Upload',
        'share': 'Share',
        'copy': 'Copy',
        'paste': 'Paste',
        'cut': 'Cut',
        'select_all': 'Select All',
        'undo': 'Undo',
        'redo': 'Redo',
        'find': 'Find',
        'replace': 'Replace',
        'goto': 'Go to',
        'line': 'Line',
        'column': 'Column',
        'word': 'Word',
        'character': 'Character',
        'zoom_in': 'Zoom In',
        'zoom_out': 'Zoom Out',
        'fullscreen': 'Fullscreen',
        'exit_fullscreen': 'Exit Fullscreen',
        'settings': 'Settings',
        'profile': 'Profile',
        'account': 'Account',
        'security': 'Security',
        'privacy': 'Privacy',
        'help_feedback': 'Help & Feedback',
        'about_us': 'About Us',
        'contact_us': 'Contact Us',
        'report_issue': 'Report an Issue',
        'send_feedback': 'Send Feedback',
        'rate_us': 'Rate Us',
        'share_app': 'Share App',
        'follow_us': 'Follow Us'
    },
    
    'auth': {
        'login_title': 'Welcome Back',
        'login_subtitle': 'Sign in to continue your journey',
        'register_title': 'Create Account',
        'register_subtitle': 'Start your journey with us',
        'reset_title': 'Reset Password',
        'reset_subtitle': 'Enter your email to reset your password',
        'email_label': 'Email Address',
        'password_label': 'Password',
        'confirm_password': 'Confirm Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_new_password': 'Confirm New Password',
        'forgot_password': 'Forgot Password?',
        'remember_me': 'Remember me',
        'no_account': "Don't have an account?",
        'has_account': 'Already have an account?',
        'sign_up': 'Sign Up',
        'sign_in': 'Sign In',
        'sign_out': 'Sign Out',
        'reset_password': 'Reset Password',
        'send_reset_link': 'Send Reset Link',
        'reset_link_sent': 'Reset link has been sent to your email',
        'check_email': 'Please check your email for the reset link',
        'password_changed': 'Password changed successfully',
        'password_mismatch': 'Passwords do not match',
        'invalid_email': 'Please enter a valid email address',
        'invalid_password': 'Password must be at least 6 characters',
        'weak_password': 'Password is too weak',
        'medium_password': 'Medium strength password',
        'strong_password': 'Strong password',
        'very_strong': 'Very strong password',
        'email_required': 'Email is required',
        'password_required': 'Password is required',
        'name_required': 'Name is required',
        'terms_required': 'You must accept the terms and conditions',
        'agree_terms': 'I agree to the Terms of Service and Privacy Policy',
        'subscribe_newsletter': 'Subscribe to newsletter',
        'social_login': 'Or continue with',
        'login_google': 'Continue with Google',
        'login_github': 'Continue with GitHub',
        'login_facebook': 'Continue with Facebook',
        'login_twitter': 'Continue with Twitter',
        'or': 'OR',
        'already_have_account': 'Already have an account? Sign In',
        'need_account': 'Need an account? Sign Up',
        'back_to_login': 'Back to Login',
        'back_to_home': 'Back to Home',
        'logout_confirm': 'Are you sure you want to logout?',
        'delete_account_confirm': 'Are you sure you want to delete your account? This action cannot be undone.',
        'account_deleted': 'Account deleted successfully',
        'account_updated': 'Account updated successfully',
        'profile_updated': 'Profile updated successfully',
        'email_verified': 'Email verified successfully',
        'verification_sent': 'Verification email sent',
        'resend_verification': 'Resend verification email',
        'change_password': 'Change Password',
        'delete_account': 'Delete Account',
        'update_profile': 'Update Profile',
        'verify_email': 'Verify Email'
    },
    
    'dashboard': {
        'title': 'Dashboard',
        'welcome_back': 'Welcome back, {name}!',
        'welcome_guest': 'Welcome, Guest!',
        'subtitle': 'Here\'s what\'s happening with your projects',
        'recent_projects': 'Recent Projects',
        'ai_chat': 'AI Chat Assistant',
        'documentation': 'Documentation',
        'coder': 'Code Editor',
        'projects_count': 'You have {count} ongoing projects',
        'files_count': '{count} files',
        'lines_count': '{count} lines of code',
        'last_edited': 'Last edited {time}',
        'created_at': 'Created {time}',
        'start_chat': 'Start Chat',
        'read_docs': 'Read Docs',
        'open_coder': 'Open Coder',
        'continue_project': 'Continue where you left off',
        'need_help': 'Need help? Chat with our AI assistant',
        'learn_more': 'Learn how to use the platform effectively',
        'quick_actions': 'Quick Actions',
        'recent_activity': 'Recent Activity',
        'view_all': 'View All',
        'no_projects': 'No projects yet. Create your first project!',
        'create_project': 'Create Project',
        'import_project': 'Import Project',
        'export_project': 'Export Project',
        'share_project': 'Share Project',
        'project_stats': 'Project Statistics',
        'total_projects': 'Total Projects',
        'total_files': 'Total Files',
        'total_lines': 'Total Lines',
        'storage_used': 'Storage Used',
        'last_login': 'Last Login',
        'account_status': 'Account Status',
        'membership': 'Membership',
        'free_trial': 'Free Trial',
        'days_left': '{days} days left',
        'upgrade_now': 'Upgrade Now',
        'whats_new': 'What\'s New',
        'view_changelog': 'View Changelog',
        'tip_of_day': 'Tip of the Day',
        'next_tip': 'Next Tip',
        'got_it': 'Got it!'
    },
    
    'chat': {
        'title': 'AI Chat Assistant',
        'new_chat': 'New Chat',
        'type_message': 'Type your message here...',
        'upload_file': 'Upload File',
        'send': 'Send',
        'thinking': 'AI is thinking...',
        'error': 'Sorry, I encountered an error. Please try again.',
        'history': 'Chat History',
        'clear_history': 'Clear History',
        'delete_chat': 'Delete Chat',
        'delete_confirm': 'Are you sure you want to delete this chat?',
        'chat_with_ai': 'Chat with AI Assistant',
        'file_uploaded': 'File uploaded: {filename}',
        'file_too_large': 'File too large. Maximum size is 10MB',
        'unsupported_file': 'Unsupported file type',
        'code_detected': 'I detected code in your message. Would you like to open it in the coder?',
        'open_in_coder': 'Open in Coder',
        'copy_code': 'Copy Code',
        'insert_code': 'Insert Code',
        'save_to_project': 'Save to Project',
        'new_project_from_chat': 'Create New Project from Chat',
        'chat_settings': 'Chat Settings',
        'temperature': 'Temperature',
        'max_tokens': 'Max Tokens',
        'model': 'AI Model',
        'system_prompt': 'System Prompt',
        'reset_settings': 'Reset to Default',
        'save_settings': 'Save Settings',
        'clear_conversation': 'Clear Conversation',
        'export_conversation': 'Export Conversation',
        'import_conversation': 'Import Conversation',
        'search_conversation': 'Search in Conversation',
        'jump_to_message': 'Jump to Message',
        'copy_message': 'Copy Message',
        'reply_to': 'Reply to',
        'edit_message': 'Edit Message',
        'delete_message': 'Delete Message',
        'pin_message': 'Pin Message',
        'unpin_message': 'Unpin Message',
        'pinned_messages': 'Pinned Messages',
        'no_pinned': 'No pinned messages',
        'share_chat': 'Share Chat',
        'share_link': 'Share Link',
        'share_as_image': 'Share as Image',
        'download_as_text': 'Download as Text',
        'download_as_json': 'Download as JSON',
        'chat_statistics': 'Chat Statistics',
        'total_messages': 'Total Messages',
        'total_tokens': 'Total Tokens',
        'average_response_time': 'Avg Response Time',
        'session_duration': 'Session Duration',
        'feedback': 'Feedback',
        'helpful': 'Helpful',
        'not_helpful': 'Not Helpful',
        'report_issue': 'Report Issue',
        'suggest_improvement': 'Suggest Improvement'
    },
    
    'coder': {
        'title': 'Code Editor',
        'new_file': 'New File',
        'new_folder': 'New Folder',
        'save': 'Save',
        'save_all': 'Save All',
        'run': 'Run',
        'stop': 'Stop',
        'debug': 'Debug',
        'preview': 'Preview',
        'terminal': 'Terminal',
        'file_explorer': 'File Explorer',
        'file_name': 'File Name',
        'file_type': 'File Type',
        'file_size': 'File Size',
        'create_file': 'Create File',
        'delete_file': 'Delete File',
        'rename_file': 'Rename File',
        'duplicate_file': 'Duplicate File',
        'download_file': 'Download File',
        'upload_file': 'Upload File',
        'unsaved_changes': 'You have unsaved changes. Save before closing?',
        'save_to_drive': 'Save to Google Drive',
        'load_from_drive': 'Load from Google Drive',
        'enter_file_name': 'Enter file name (with extension):',
        'enter_folder_name': 'Enter folder name:',
        'select_language': 'Select Language',
        'html': 'HTML',
        'css': 'CSS',
        'javascript': 'JavaScript',
        'typescript': 'TypeScript',
        'jsx': 'JSX',
        'tsx': 'TSX',
        'python': 'Python',
        'java': 'Java',
        'cpp': 'C++',
        'c': 'C',
        'csharp': 'C#',
        'php': 'PHP',
        'ruby': 'Ruby',
        'go': 'Go',
        'rust': 'Rust',
        'swift': 'Swift',
        'kotlin': 'Kotlin',
        'dart': 'Dart',
        'sql': 'SQL',
        'json': 'JSON',
        'xml': 'XML',
        'yaml': 'YAML',
        'markdown': 'Markdown',
        'plain_text': 'Plain Text',
        'recent_files': 'Recent Files',
        'open_file': 'Open File',
        'close_file': 'Close File',
        'close_all': 'Close All',
        'close_others': 'Close Others',
        'close_saved': 'Close Saved',
        'next_tab': 'Next Tab',
        'previous_tab': 'Previous Tab',
        'split_editor': 'Split Editor',
        'split_vertical': 'Split Vertical',
        'split_horizontal': 'Split Horizontal',
        'remove_split': 'Remove Split',
        'toggle_word_wrap': 'Toggle Word Wrap',
        'toggle_minimap': 'Toggle Minimap',
        'toggle_line_numbers': 'Toggle Line Numbers',
        'toggle_fold': 'Toggle Fold',
        'fold_all': 'Fold All',
        'unfold_all': 'Unfold All',
        'format_document': 'Format Document',
        'format_selection': 'Format Selection',
        'find': 'Find',
        'replace': 'Replace',
        'find_in_files': 'Find in Files',
        'replace_in_files': 'Replace in Files',
        'goto_line': 'Go to Line',
        'goto_symbol': 'Go to Symbol',
        'goto_file': 'Go to File',
        'command_palette': 'Command Palette',
        'toggle_comment': 'Toggle Comment',
        'add_comment': 'Add Comment',
        'remove_comment': 'Remove Comment',
        'indent': 'Indent',
        'outdent': 'Outdent',
        'move_lines_up': 'Move Lines Up',
        'move_lines_down': 'Move Lines Down',
        'copy_lines_up': 'Copy Lines Up',
        'copy_lines_down': 'Copy Lines Down',
        'delete_lines': 'Delete Lines',
        'join_lines': 'Join Lines',
        'transpose': 'Transpose',
        'to_uppercase': 'To Uppercase',
        'to_lowercase': 'To Lowercase',
        'to_titlecase': 'To Title Case',
        'sort_lines': 'Sort Lines',
        'reverse_lines': 'Reverse Lines',
        'shuffle_lines': 'Shuffle Lines',
        'remove_duplicate_lines': 'Remove Duplicate Lines',
        'trim_trailing_whitespace': 'Trim Trailing Whitespace',
        'remove_empty_lines': 'Remove Empty Lines',
        'convert_indentation': 'Convert Indentation',
        'spaces_to_tabs': 'Spaces to Tabs',
        'tabs_to_spaces': 'Tabs to Spaces',
        'project_settings': 'Project Settings',
        'editor_settings': 'Editor Settings',
        'terminal_settings': 'Terminal Settings',
        'preview_settings': 'Preview Settings',
        'font_size': 'Font Size',
        'font_family': 'Font Family',
        'tab_size': 'Tab Size',
        'insert_spaces': 'Insert Spaces',
        'auto_save': 'Auto Save',
        'auto_save_delay': 'Auto Save Delay (ms)',
        'render_whitespace': 'Render Whitespace',
        'render_control_characters': 'Render Control Characters',
        'render_line_highlight': 'Render Line Highlight',
        'match_brackets': 'Match Brackets',
        'auto_close_brackets': 'Auto Close Brackets',
        'auto_close_tags': 'Auto Close Tags',
        'auto_surround': 'Auto Surround',
        'drag_and_drop': 'Drag and Drop',
        'code_lens': 'Code Lens',
        'color_decorators': 'Color Decorators',
        'folding': 'Folding',
        'folding_strategy': 'Folding Strategy',
        'show_folding_controls': 'Show Folding Controls',
        'linked_editing': 'Linked Editing',
        'accept_suggestion_on_enter': 'Accept Suggestion on Enter',
        'snippet_suggestions': 'Snippet Suggestions',
        'word_based_suggestions': 'Word Based Suggestions',
        'quick_suggestions': 'Quick Suggestions',
        'quick_suggestions_delay': 'Quick Suggestions Delay (ms)',
        'parameter_hints': 'Parameter Hints',
        'parameter_hints_delay': 'Parameter Hints Delay (ms)',
        'auto_complete': 'Auto Complete',
        'auto_complete_delay': 'Auto Complete Delay (ms)',
        'hover': 'Hover',
        'hover_delay': 'Hover Delay (ms)',
        'code_actions': 'Code Actions',
        'code_actions_on_save': 'Code Actions on Save',
        'format_on_save': 'Format on Save',
        'format_on_paste': 'Format on Paste',
        'format_on_type': 'Format on Type',
        'minimap': 'Minimap',
        'minimap_side': 'Minimap Side',
        'minimap_size': 'Minimap Size',
        'minimap_show_slider': 'Show Minimap Slider',
        'breadcrumbs': 'Breadcrumbs',
        'breadcrumbs_enabled': 'Enable Breadcrumbs',
        'breadcrumbs_file_path': 'Show File Path',
        'breadcrumbs_symbols': 'Show Symbols',
        'sticky_scroll': 'Sticky Scroll',
        'sticky_scroll_enabled': 'Enable Sticky Scroll',
        'sticky_scroll_max_lines': 'Max Sticky Lines',
        'cursor_blinking': 'Cursor Blinking',
        'cursor_style': 'Cursor Style',
        'cursor_width': 'Cursor Width',
        'mouse_wheel_zoom': 'Mouse Wheel Zoom',
        'mouse_wheel_scroll_speed': 'Mouse Wheel Scroll Speed',
        'smooth_scrolling': 'Smooth Scrolling',
        'scroll_beyond_last_line': 'Scroll Beyond Last Line',
        'scroll_beyond_last_column': 'Scroll Beyond Last Column',
        'word_separators': 'Word Separators',
        'word_wrap': 'Word Wrap',
        'word_wrap_column': 'Word Wrap Column',
        'word_wrap_minified': 'Word Wrap Minified',
        'wrapping_indent': 'Wrapping Indent',
        'wrapping_strategy': 'Wrapping Strategy'
    },
    
    'terminal': {
        'title': 'Terminal',
        'new_terminal': 'New Terminal',
        'close_terminal': 'Close Terminal',
        'clear_terminal': 'Clear Terminal',
        'copy': 'Copy',
        'paste': 'Paste',
        'select_all': 'Select All',
        'find': 'Find',
        'split_terminal': 'Split Terminal',
        'split_vertical': 'Split Vertical',
        'split_horizontal': 'Split Horizontal',
        'remove_split': 'Remove Split',
        'rename_terminal': 'Rename Terminal',
        'terminal_settings': 'Terminal Settings',
        'font_family': 'Font Family',
        'font_size': 'Font Size',
        'line_height': 'Line Height',
        'cursor_blink': 'Cursor Blink',
        'cursor_style': 'Cursor Style',
        'scrollback': 'Scrollback',
        'shell_path': 'Shell Path',
        'shell_args': 'Shell Arguments',
        'env_variables': 'Environment Variables',
        'working_directory': 'Working Directory',
        'open_in_new_tab': 'Open in New Tab',
        'open_in_new_window': 'Open in New Window',
        'open_in_editor': 'Open in Editor',
        'run_command': 'Run Command',
        'stop_command': 'Stop Command',
        'restart_command': 'Restart Command',
        'kill_process': 'Kill Process',
        'interrupt_process': 'Interrupt Process (Ctrl+C)',
        'suspend_process': 'Suspend Process (Ctrl+Z)',
        'resume_process': 'Resume Process',
        'background_jobs': 'Background Jobs',
        'foreground_job': 'Foreground Job',
        'job_control': 'Job Control',
        'process_list': 'Process List',
        'process_id': 'Process ID',
        'process_name': 'Process Name',
        'process_status': 'Process Status',
        'process_cpu': 'CPU %',
        'process_memory': 'Memory',
        'process_time': 'Time',
        'kill_process_confirm': 'Are you sure you want to kill process {pid}?',
        'terminate_process_confirm': 'Are you sure you want to terminate process {pid}?',
        'command_not_found': 'Command not found: {command}',
        'permission_denied': 'Permission denied',
        'file_not_found': 'File not found: {file}',
        'directory_not_found': 'Directory not found: {dir}',
        'command_history': 'Command History',
        'clear_history': 'Clear History',
        'search_history': 'Search History',
        'export_history': 'Export History',
        'import_history': 'Import History',
        'working_directory': 'Working Directory: {dir}',
        'current_user': 'Current User: {user}',
        'hostname': 'Hostname: {host}',
        'uptime': 'Uptime: {uptime}',
        'system_info': 'System Information',
        'disk_usage': 'Disk Usage',
        'memory_usage': 'Memory Usage',
        'network_info': 'Network Information',
        'environment': 'Environment Variables',
        'aliases': 'Aliases',
        'functions': 'Functions',
        'history_size': 'History Size: {size}',
        'last_command': 'Last Command: {command}',
        'exit_code': 'Exit Code: {code}',
        'execution_time': 'Execution Time: {time}ms',
        'welcome_message': 'Welcome to amkyaw.dev Terminal v2.0.0',
        'help_message': 'Type \'help\' to see available commands',
        'goodbye_message': 'Goodbye! Terminal closed'
    },
    
    'program_viewer': {
        'title': 'Program Viewer',
        'file_info': 'File Information',
        'file_name': 'File Name: {name}',
        'file_size': 'File Size: {size}',
        'file_type': 'File Type: {type}',
        'created': 'Created: {date}',
        'modified': 'Modified: {date}',
        'accessed': 'Accessed: {date}',
        'line_count': 'Lines: {count}',
        'word_count': 'Words: {count}',
        'character_count': 'Characters: {count}',
        'encoding': 'Encoding: {encoding}',
        'mime_type': 'MIME Type: {mime}',
        'permissions': 'Permissions: {perms}',
        'owner': 'Owner: {owner}',
        'group': 'Group: {group}',
        'download': 'Download',
        'print': 'Print',
        'view_source': 'View Source',
        'view_rendered': 'View Rendered',
        'toggle_word_wrap': 'Toggle Word Wrap',
        'toggle_line_numbers': 'Toggle Line Numbers',
        'toggle_syntax_highlighting': 'Toggle Syntax Highlighting',
        'increase_font_size': 'Increase Font Size',
        'decrease_font_size': 'Decrease Font Size',
        'reset_font_size': 'Reset Font Size',
        'fullscreen': 'Fullscreen',
        'exit_fullscreen': 'Exit Fullscreen',
        'zoom_in': 'Zoom In',
        'zoom_out': 'Zoom Out',
        'reset_zoom': 'Reset Zoom',
        'rotate': 'Rotate',
        'flip_horizontal': 'Flip Horizontal',
        'flip_vertical': 'Flip Vertical',
        'next_page': 'Next Page',
        'previous_page': 'Previous Page',
        'goto_page': 'Go to Page',
        'page': 'Page {current} of {total}',
        'find_in_file': 'Find in File',
        'replace_in_file': 'Replace in File',
        'jump_to_line': 'Jump to Line',
        'bookmark': 'Bookmark',
        'add_bookmark': 'Add Bookmark',
        'remove_bookmark': 'Remove Bookmark',
        'next_bookmark': 'Next Bookmark',
        'previous_bookmark': 'Previous Bookmark',
        'bookmark_list': 'Bookmarks',
        'no_bookmarks': 'No bookmarks',
        'export_as_pdf': 'Export as PDF',
        'export_as_html': 'Export as HTML',
        'export_as_txt': 'Export as TXT',
        'export_as_rtf': 'Export as RTF',
        'share_file': 'Share File',
        'copy_path': 'Copy Path',
        'copy_content': 'Copy Content',
        'open_in_editor': 'Open in Editor',
        'open_in_terminal': 'Open in Terminal',
        'reveal_in_explorer': 'Reveal in Explorer',
        'properties': 'Properties'
    },
    
    'docs': {
        'title': 'Documentation',
        'search': 'Search documentation...',
        'search_results': 'Search Results',
        'no_results': 'No results found for "{query}"',
        'categories': 'Categories',
        'all': 'All',
        'getting_started': 'Getting Started',
        'coder': 'Code Editor',
        'chat': 'AI Chat',
        'terminal': 'Terminal',
        'projects': 'Projects',
        'api': 'API Reference',
        'tutorials': 'Tutorials',
        'faq': 'Frequently Asked Questions',
        'examples': 'Code Examples',
        'quick_start': 'Quick Start Guide',
        'copy': 'Copy',
        'copied': 'Copied!',
        'copy_code': 'Copy Code',
        'run_example': 'Run Example',
        'open_in_coder': 'Open in Coder',
        'download_example': 'Download Example',
        'view_on_github': 'View on GitHub',
        'report_issue': 'Report Issue',
        'edit_page': 'Edit this Page',
        'last_updated': 'Last updated: {date}',
        'next_topic': 'Next Topic',
        'previous_topic': 'Previous Topic',
        'table_of_contents': 'Table of Contents',
        'on_this_page': 'On this page',
        'related_topics': 'Related Topics',
        'need_more_help': 'Need more help?',
        'join_community': 'Join our Community',
        'ask_forum': 'Ask in Forum',
        'contact_support': 'Contact Support',
        'was_this_helpful': 'Was this helpful?',
        'yes': 'Yes',
        'no': 'No',
        'feedback_prompt': 'How can we improve this documentation?',
        'submit_feedback': 'Submit Feedback',
        'thanks_feedback': 'Thank you for your feedback!',
        'popular_topics': 'Popular Topics',
        'recent_updates': 'Recent Updates',
        'version': 'Version: {version}',
        'documentation_for': 'Documentation for {version}',
        'switch_version': 'Switch Version',
        'dark_mode': 'Dark Mode',
        'light_mode': 'Light Mode',
        'print_page': 'Print this Page',
        'share_page': 'Share this Page',
        'copy_link': 'Copy Link',
        'link_copied': 'Link copied to clipboard'
    },
    
    'about': {
        'title': 'About Us',
        'subtitle': 'Empowering developers with AI-powered tools',
        'mission': 'Our Mission',
        'mission_text': 'To make coding accessible to everyone through intelligent tools and AI assistance.',
        'vision': 'Our Vision',
        'vision_text': 'Create a world where anyone can bring their ideas to life through code.',
        'values': 'Our Values',
        'value_innovation': 'Innovation',
        'value_innovation_desc': 'Constantly pushing boundaries and exploring new possibilities',
        'value_quality': 'Quality',
        'value_quality_desc': 'Delivering the best experience through attention to detail',
        'value_community': 'Community',
        'value_community_desc': 'Building together with our users and contributors',
        'value_accessibility': 'Accessibility',
        'value_accessibility_desc': 'Making development tools available to everyone',
        'founder': 'Founder & Lead Developer',
        'founder_name': 'Aung Thu Rain',
        'founder_title': 'Founder & Lead Developer',
        'founder_bio': 'Passionate developer with a vision to make coding accessible to everyone. Creating tools that combine AI with web development to simplify the learning and development process.',
        'team': 'Our Team',
        'team_members': 'Team Members',
        'join_team': 'Join Our Team',
        'stats_users': 'Active Users',
        'stats_projects': 'Projects Created',
        'stats_conversations': 'AI Conversations',
        'stats_tutorials': 'Tutorials',
        'stats_countries': 'Countries',
        'stats_partners': 'Partners',
        'features': 'Why Choose Us',
        'feature_ai': 'AI-Powered',
        'feature_ai_desc': 'Get intelligent code suggestions and debugging help',
        'feature_cloud': 'Cloud Storage',
        'feature_cloud_desc': 'Save and sync projects with Google Drive',
        'feature_multi_lang': 'Multi-Language',
        'feature_multi_lang_desc': 'Support for 20+ programming languages',
        'feature_responsive': 'Responsive Design',
        'feature_responsive_desc': 'Perfect experience on all devices',
        'feature_realtime': 'Real-time Preview',
        'feature_realtime_desc': 'See your changes instantly',
        'feature_collaboration': 'Collaboration',
        'feature_collaboration_desc': 'Work together with your team',
        'journey': 'Our Journey',
        'journey_2023': 'Project Started',
        'journey_2023_desc': 'Initial concept and development began with a vision to create an AI-powered coding platform.',
        'journey_2024': 'Beta Launch',
        'journey_2024_desc': 'Released beta version with core features: code editor, AI chat, and project management.',
        'journey_2025': 'Full Release',
        'journey_2025_desc': 'Official launch with Google Drive integration, multi-language support, and mobile apps.',
        'milestones': 'Milestones',
        'testimonials': 'What Our Users Say',
        'testimonial_1': 'amkyaw.dev has transformed how I learn coding. The AI assistant is incredibly helpful!',
        'testimonial_1_author': 'John Doe',
        'testimonial_1_title': 'Web Developer',
        'testimonial_2': 'Best code editor I\'ve used. The real-time preview and Google Drive sync are game changers.',
        'testimonial_2_author': 'Jane Smith',
        'testimonial_2_title': 'Software Engineer',
        'testimonial_3': 'The multi-language support and terminal emulator make it perfect for all my projects.',
        'testimonial_3_author': 'Mike Johnson',
        'testimonial_3_title': 'DevOps Engineer',
        'contact': 'Contact Us',
        'email': 'Email',
        'phone': 'Phone',
        'address': 'Address',
        'address_details': 'Naypyidaw, Myanmar',
        'follow_us': 'Follow Us',
        'github': 'GitHub',
        'twitter': 'Twitter',
        'linkedin': 'LinkedIn',
        'facebook': 'Facebook',
        'youtube': 'YouTube',
        'discord': 'Discord',
        'slack': 'Slack',
        'newsletter': 'Subscribe to Newsletter',
        'newsletter_placeholder': 'Enter your email',
        'newsletter_button': 'Subscribe',
        'newsletter_success': 'Successfully subscribed!',
        'privacy_policy': 'Privacy Policy',
        'terms_of_service': 'Terms of Service',
        'cookie_policy': 'Cookie Policy',
        'copyright': '© {year} amkyaw.dev. All rights reserved.'
    },
    
    'admin': {
        'title': 'Admin Panel',
        'subtitle': 'Manage your platform and users',
        'dashboard': 'Admin Dashboard',
        'overview': 'Overview',
        'users': 'User Management',
        'projects': 'Project Management',
        'analytics': 'Analytics',
        'settings': 'Platform Settings',
        'logs': 'System Logs',
        'backup': 'Backup & Restore',
        'security': 'Security',
        'updates': 'Updates',
        'plugins': 'Plugins',
        'themes': 'Themes',
        'languages': 'Languages',
        'notifications': 'Notifications',
        'email_templates': 'Email Templates',
        'api_keys': 'API Keys',
        'webhooks': 'Webhooks',
        'integrations': 'Integrations',
        'maintenance': 'Maintenance Mode',
        'statistics': 'Platform Statistics',
        'total_users': 'Total Users',
        'new_users_today': 'New Users Today',
        'active_users': 'Active Users',
        'total_projects': 'Total Projects',
        'projects_today': 'Projects Created Today',
        'total_chats': 'Total AI Chats',
        'chats_today': 'AI Chats Today',
        'total_lines': 'Lines of Code',
        'storage_used': 'Storage Used',
        'bandwidth': 'Bandwidth',
        'api_calls': 'API Calls',
        'response_time': 'Avg Response Time',
        'uptime': 'Uptime',
        'server_status': 'Server Status',
        'database_status': 'Database Status',
        'cache_status': 'Cache Status',
        'queue_status': 'Queue Status',
        'storage_status': 'Storage Status',
        'email_status': 'Email Service',
        'sms_status': 'SMS Service',
        'ai_service': 'AI Service',
        'google_drive': 'Google Drive Sync',
        'recent_activity': 'Recent Activity',
        'view_all_activity': 'View All Activity',
        'user_registrations': 'User Registrations',
        'project_creations': 'Project Creations',
        'chat_sessions': 'Chat Sessions',
        'error_logs': 'Error Logs',
        'warning_logs': 'Warning Logs',
        'info_logs': 'Info Logs',
        'debug_logs': 'Debug Logs',
        'system_info': 'System Information',
        'php_version': 'PHP Version',
        'mysql_version': 'MySQL Version',
        'node_version': 'Node.js Version',
        'server_software': 'Server Software',
        'server_os': 'Server OS',
        'server_time': 'Server Time',
        'timezone': 'Timezone',
        'memory_limit': 'Memory Limit',
        'max_execution_time': 'Max Execution Time',
        'upload_max_filesize': 'Upload Max Filesize',
        'post_max_size': 'Post Max Size',
        'maintenance_mode': 'Maintenance Mode',
        'enable_maintenance': 'Enable Maintenance Mode',
        'disable_maintenance': 'Disable Maintenance Mode',
        'maintenance_message': 'Maintenance Message',
        'allow_ips': 'Allowed IPs',
        'backup_now': 'Backup Now',
        'restore_backup': 'Restore Backup',
        'download_backup': 'Download Backup',
        'delete_backup': 'Delete Backup',
        'scheduled_backups': 'Scheduled Backups',
        'backup_frequency': 'Backup Frequency',
        'backup_retention': 'Backup Retention',
        'last_backup': 'Last Backup',
        'backup_size': 'Backup Size',
        'security_settings': 'Security Settings',
        'two_factor_auth': 'Two-Factor Authentication',
        'recaptcha': 'reCAPTCHA',
        'rate_limiting': 'Rate Limiting',
        'ip_whitelist': 'IP Whitelist',
        'ip_blacklist': 'IP Blacklist',
        'session_timeout': 'Session Timeout',
        'password_policy': 'Password Policy',
        'min_password_length': 'Minimum Password Length',
        'require_special_chars': 'Require Special Characters',
        'require_numbers': 'Require Numbers',
        'require_uppercase': 'Require Uppercase Letters',
        'password_expiry': 'Password Expiry (days)',
        'login_attempts': 'Max Login Attempts',
        'lockout_duration': 'Lockout Duration (minutes)',
        'email_verification': 'Email Verification',
        'phone_verification': 'Phone Verification',
        'captcha_on_login': 'CAPTCHA on Login',
        'captcha_on_register': 'CAPTCHA on Registration',
        'email_settings': 'Email Settings',
        'smtp_host': 'SMTP Host',
        'smtp_port': 'SMTP Port',
        'smtp_username': 'SMTP Username',
        'smtp_password': 'SMTP Password',
        'smtp_encryption': 'SMTP Encryption',
        'from_email': 'From Email',
        'from_name': 'From Name',
        'test_email': 'Send Test Email',
        'email_logs': 'Email Logs',
        'plugin_manager': 'Plugin Manager',
        'installed_plugins': 'Installed Plugins',
        'available_plugins': 'Available Plugins',
        'install_plugin': 'Install Plugin',
        'uninstall_plugin': 'Uninstall Plugin',
        'activate_plugin': 'Activate Plugin',
        'deactivate_plugin': 'Deactivate Plugin',
        'update_plugin': 'Update Plugin',
        'plugin_settings': 'Plugin Settings',
        'theme_manager': 'Theme Manager',
        'active_theme': 'Active Theme',
        'installed_themes': 'Installed Themes',
        'available_themes': 'Available Themes',
        'install_theme': 'Install Theme',
        'uninstall_theme': 'Uninstall Theme',
        'activate_theme': 'Activate Theme',
        'customize_theme': 'Customize Theme',
        'language_manager': 'Language Manager',
        'default_language': 'Default Language',
        'available_languages': 'Available Languages',
        'install_language': 'Install Language',
        'uninstall_language': 'Uninstall Language',
        'update_translations': 'Update Translations',
        'export_translations': 'Export Translations',
        'import_translations': 'Import Translations',
        'user_roles': 'User Roles',
        'permissions': 'Permissions',
        'create_role': 'Create Role',
        'edit_role': 'Edit Role',
        'delete_role': 'Delete Role',
        'role_name': 'Role Name',
        'role_description': 'Role Description',
        'users_with_role': 'Users with this Role',
        'administrator': 'Administrator',
        'moderator': 'Moderator',
        'editor': 'Editor',
        'author': 'Author',
        'contributor': 'Contributor',
        'subscriber': 'Subscriber',
        'banned': 'Banned',
        'user_details': 'User Details',
        'user_id': 'User ID',
        'username': 'Username',
        'display_name': 'Display Name',
        'user_role': 'User Role',
        'user_status': 'User Status',
        'registration_date': 'Registration Date',
        'last_login': 'Last Login',
        'last_ip': 'Last IP',
        'email_verified': 'Email Verified',
        'phone_verified': 'Phone Verified',
        'two_factor_enabled': '2FA Enabled',
        'account_actions': 'Account Actions',
        'activate_account': 'Activate Account',
        'deactivate_account': 'Deactivate Account',
        'suspend_account': 'Suspend Account',
        'ban_account': 'Ban Account',
        'delete_account': 'Delete Account',
        'send_welcome_email': 'Send Welcome Email',
        'reset_password': 'Reset Password',
        'impersonate_user': 'Impersonate User',
        'export_user_data': 'Export User Data',
        'user_activity_log': 'User Activity Log',
        'user_projects': 'User Projects',
        'user_chats': 'User Chats',
        'user_files': 'User Files',
        'project_details': 'Project Details',
        'project_id': 'Project ID',
        'project_name': 'Project Name',
        'project_owner': 'Project Owner',
        'project_created': 'Created',
        'project_modified': 'Last Modified',
        'project_size': 'Project Size',
        'project_files': 'Files',
        'project_visibility': 'Visibility',
        'public': 'Public',
        'private': 'Private',
        'shared': 'Shared',
        'featured': 'Featured',
        'project_actions': 'Project Actions',
        'delete_project': 'Delete Project',
        'make_public': 'Make Public',
        'make_private': 'Make Private',
        'feature_project': 'Feature Project',
        'unfeature_project': 'Unfeature Project',
        'analytics_overview': 'Analytics Overview',
        'time_range': 'Time Range',
        'today': 'Today',
        'yesterday': 'Yesterday',
        'last_7_days': 'Last 7 Days',
        'last_30_days': 'Last 30 Days',
        'this_month': 'This Month',
        'last_month': 'Last Month',
        'this_year': 'This Year',
        'custom_range': 'Custom Range',
        'apply': 'Apply',
        'reset': 'Reset',
        'export_report': 'Export Report',
        'chart_users': 'Users Over Time',
        'chart_projects': 'Projects Over Time',
        'chart_chats': 'Chats Over Time',
        'chart_api': 'API Calls Over Time',
        'top_countries': 'Top Countries',
        'top_languages': 'Top Languages',
        'top_projects': 'Top Projects',
        'top_users': 'Top Users',
        'browser_stats': 'Browser Statistics',
        'device_stats': 'Device Statistics',
        'os_stats': 'Operating System Statistics',
        'referrer_stats': 'Referrer Statistics'
    },
    
    'errors': {
        '404_title': 'Page Not Found',
        '404_message': "Oops! The page you're looking for doesn't exist or has been moved.",
        '403_title': 'Access Denied',
        '403_message': "Sorry, you don't have permission to access this page.",
        '500_title': 'Server Error',
        '500_message': 'Something went wrong on our end. Please try again later.',
        '503_title': 'Service Unavailable',
        '503_message': 'The service is temporarily unavailable. Please try again soon.',
        'offline_title': 'You\'re Offline',
        'offline_message': 'Please check your internet connection and try again.',
        'back_home': 'Back to Home',
        'go_dashboard': 'Go to Dashboard',
        'try_again': 'Try Again',
        'search': 'Search for something...',
        'report_issue': 'Report this Issue',
        'contact_support': 'Contact Support',
        'error_code': 'Error Code: {code}',
        'error_details': 'Error Details: {details}',
        'request_id': 'Request ID: {id}',
        'timestamp': 'Time: {time}',
        'stack_trace': 'Stack Trace',
        'copy_error': 'Copy Error Details',
        'error_copied': 'Error details copied to clipboard'
    }
};