// Myanmar translations
window.translations = {
    'common': {
        'welcome': 'ကြိုဆိုပါတယ်',
        'login': 'ဝင်ရောက်ရန်',
        'logout': 'ထွက်ရန်',
        'register': 'စာရင်းသွင်းရန်',
        'dashboard': 'ဒက်ရှ်ဘုတ်',
        'settings': 'ဆက်တင်များ',
        'save': 'သိမ်းရန်',
        'cancel': 'ဖျက်သိမ်းရန်',
        'delete': 'ဖျက်ရန်',
        'edit': 'ပြင်ဆင်ရန်',
        'search': 'ရှာဖွေရန်',
        'loading': 'ဖွင့်နေသည်...',
        'error': 'အမှား',
        'success': 'အောင်မြင်သည်',
        'confirm': 'အတည်ပြုရန်',
        'back': 'နောက်သို့',
        'next': 'ရှေ့သို့',
        'finish': 'ပြီးဆုံးသည်'
    },
    
    'auth': {
        'login_title': 'ပြန်လည်ကြိုဆိုပါတယ်',
        'login_subtitle': 'ဆက်လက်ရန် ဝင်ရောက်ပါ',
        'register_title': 'အကောင့်ဖွင့်ရန်',
        'register_subtitle': 'သင်၏ခရီးစဉ်ကို စတင်ပါ',
        'email': 'အီးမေးလ်',
        'password': 'စကားဝှက်',
        'confirm_password': 'စကားဝှက်အတည်ပြုရန်',
        'forgot_password': 'စကားဝှက်မေ့နေပါသလား?',
        'no_account': 'အကောင့်မရှိသေးဘူးလား?',
        'has_account': 'အကောင့်ရှိပြီးသားလား?',
        'sign_up': 'စာရင်းသွင်းရန်',
        'sign_in': 'ဝင်ရောက်ရန်',
        'reset_password': 'စကားဝှက်ပြန်လည်သတ်မှတ်ရန်',
        'reset_sent': 'ပြန်လည်သတ်မှတ်ရန်လင့်ခ်ကို သင့်အီးမေးလ်သို့ ပို့လိုက်ပါပြီ',
        'password_mismatch': 'စကားဝှက်များ မတူညီပါ',
        'invalid_email': 'အီးမေးလ်လိပ်စာ မမှန်ကန်ပါ',
        'weak_password': 'စကားဝှက် အားနည်းလွန်းသည်'
    },
    
    'dashboard': {
        'title': 'ဒက်ရှ်ဘုတ်',
        'welcome_back': 'ပြန်လည်ကြိုဆိုပါတယ် {name} !',
        'recent_projects': 'မကြာသေးမီက ပရောဂျက်များ',
        'ai_chat': 'AI ချတ်အကူ',
        'documentation': 'စာရွက်စာတမ်းများ',
        'projects_count': 'သင့်တွင် လက်ရှိလုပ်ဆောင်နေသော ပရောဂျက် {count} ခုရှိသည်',
        'start_chat': 'ချတ်စတင်ရန်',
        'read_docs': 'စာရွက်စာတမ်းဖတ်ရန်',
        'open_coder': 'ကုဒ်အယ်ဒီတာဖွင့်ရန်',
        'continue_project': 'ယခင်ရပ်ထားသည့်နေရာမှ ဆက်လုပ်ရန်',
        'need_help': 'အကူအညီလိုပါသလား? AI အကူနှင့် ချတ်လုပ်ပါ',
        'learn_more': 'ပလက်ဖောင်းကို ထိရောက်စွာအသုံးပြုနည်း လေ့လာရန်'
    },
    
    'chat': {
        'title': 'AI ချတ်',
        'new_chat': 'ချတ်အသစ်',
        'type_message': 'စာရိုက်ပါ...',
        'upload_file': 'ဖိုင်တင်ရန်',
        'send': 'ပို့ရန်',
        'thinking': 'စဉ်းစားနေသည်...',
        'error': 'တောင်းပန်ပါတယ်။ အမှားတစ်ခုဖြစ်သွားပါတယ်။ ထပ်စမ်းကြည့်ပါ။',
        'history': 'ချတ်မှတ်တမ်း',
        'clear_history': 'မှတ်တမ်းရှင်းရန်',
        'delete_chat': 'ချတ်ဖျက်ရန်',
        'chat_with_ai': 'AI အကူနှင့် ချတ်လုပ်ရန်',
        'file_uploaded': 'ဖိုင်တင်ပြီးပါပြီ: {filename}',
        'code_detected': 'ကုဒ်တွေ့ရှိပါသည်။ ကုဒ်အယ်ဒီတာတွင် ဖွင့်ကြည့်မလား?'
    },
    
    'coder': {
        'title': 'ကုဒ်အယ်ဒီတာ',
        'new_file': 'ဖိုင်အသစ်',
        'new_folder': 'ဖိုလ်ဒါအသစ်',
        'save': 'သိမ်းရန်',
        'save_all': 'အားလုံးသိမ်းရန်',
        'run': 'Run',
        'stop': 'Stop',
        'preview': 'အစမ်းကြည့်ရန်',
        'terminal': 'Terminal',
        'file_explorer': 'ဖိုင်ရှာဖွေရန်',
        'file_name': 'ဖိုင်အမည်',
        'file_type': 'ဖိုင်အမျိုးအစား',
        'create_file': 'ဖိုင်ဖန်တီးရန်',
        'delete_file': 'ဖိုင်ဖျက်ရန်',
        'rename_file': 'ဖိုင်အမည်ပြောင်းရန်',
        'unsaved_changes': 'သိမ်းမထားသော အပြောင်းအလဲများရှိသည်',
        'save_to_drive': 'Drive သို့သိမ်းရန်',
        'load_from_drive': 'Drive မှဖွင့်ရန်',
        'enter_file_name': 'ဖိုင်အမည်ထည့်ပါ (extension အပါအဝင်):',
        'select_language': 'ဘာသာစကားရွေးချယ်ရန်',
        'html': 'HTML',
        'css': 'CSS',
        'javascript': 'JavaScript',
        'python': 'Python',
        'json': 'JSON',
        'markdown': 'Markdown'
    },
    
    'settings': {
        'title': 'ဆက်တင်များ',
        'profile': 'ပရိုဖိုင်ဆက်တင်များ',
        'appearance': 'အသွင်အပြင်',
        'language': 'ဘာသာစကား',
        'notifications': 'အသိပေးချက်များ',
        'privacy': 'ကိုယ်ရေးလုံခြုံမှု',
        'account': 'အကောင့်',
        'display_name': 'ပြသမည့်အမည်',
        'email': 'အီးမေးလ်',
        'gender': 'လိင်',
        'male': 'အမျိုးသား',
        'female': 'အမျိုးသမီး',
        'other': 'အခြား',
        'prefer_not': 'ဖော်ပြလိုမှုမရှိ',
        'bio': 'ကိုယ်ရေးအကျဉ်း',
        'avatar': 'ကိုယ်ပိုင်ပုံရွေးချယ်ရန်',
        'dark_mode': 'အမှောင်မုဒ်',
        'compact_view': 'ကျစ်လစ်သောမြင်ကွင်း',
        'save_changes': 'အပြောင်းအလဲများသိမ်းရန်',
        'change_password': 'စကားဝှက်ပြောင်းရန်',
        'delete_account': 'အကောင့်ဖျက်ရန်',
        'current_password': 'လက်ရှိစကားဝှက်',
        'new_password': 'စကားဝှက်အသစ်',
        'confirm_new_password': 'စကားဝှက်အသစ်အတည်ပြုရန်'
    },
    
    'docs': {
        'title': 'စာရွက်စာတမ်းများ',
        'search': 'စာရွက်စာတမ်းများရှာဖွေရန်...',
        'categories': 'အမျိုးအစားများ',
        'all': 'အားလုံး',
        'getting_started': 'စတင်အသုံးပြုခြင်း',
        'coder': 'ကုဒ်အယ်ဒီတာ',
        'chat': 'AI ချတ်',
        'api': 'API',
        'tutorials': 'သင်ခန်းစာများ',
        'quick_start': 'အမြန်စတင်ရန်လမ်းညွှန်',
        'faq': 'မေးလေ့ရှိသောမေးခွန်းများ',
        'examples': 'ကုဒ်နမူနာများ',
        'copy': 'ကူးယူရန်',
        'copied': 'ကူးယူပြီးပါပြီ'
    },
    
    'about': {
        'title': 'ကျွန်ုပ်တို့အကြောင်း',
        'subtitle': 'AI စွမ်းအားသုံးကိရိယာများဖြင့် developer များကို စွမ်းဆောင်နိုင်စေခြင်း',
        'founder': 'တည်ထောင်သူနှင့် ဦးဆောင် developer',
        'stats': {
            'users': 'တက်ကြွသောအသုံးပြုသူများ',
            'projects': 'ဖန်တီးပြီးသော ပရောဂျက်များ',
            'conversations': 'AI စကားပြောဆိုမှုများ',
            'tutorials': 'သင်ခန်းစာများ'
        },
        'features': {
            'ai_powered': 'AI စွမ်းအားသုံး',
            'ai_desc': 'ကုဒ်အကြံပြုချက်များနှင့် အမှားရှာပြင်ခြင်းများ ရယူပါ',
            'cloud': 'Cloud သိုလှောင်မှု',
            'cloud_desc': 'Google Drive ဖြင့် ပရောဂျက်များကို သိမ်းဆည်းပြီး ထပ်တူပြုလုပ်ပါ',
            'multi_lang': 'ဘာသာစုံ',
            'multi_lang_desc': 'HTML, CSS, JS, Python နှင့် အခြားအရာများအတွက် ပံ့ပိုးမှု',
            'responsive': 'တုံ့ပြန်မှုရှိသော',
            'responsive_desc': 'စက်ပစ္စည်းအားလုံးတွင် ကောင်းမွန်သောအတွေ့အကြုံ'
        },
        'journey': 'ကျွန်ုပ်တို့၏ခရီးစဉ်',
        'team': 'ကျွန်ုပ်တို့၏အဖွဲ့'
    },
    
    'admin': {
        'title': 'အက်မင် panel',
        'subtitle': 'သင်၏ပလက်ဖောင်းနှင့် အသုံးပြုသူများကို စီမံခန့်ခွဲရန်',
        'total_users': 'စုစုပေါင်းအသုံးပြုသူများ',
        'projects': 'ပရောဂျက်များ',
        'conversations': 'AI စကားပြောဆိုမှုများ',
        'avg_session': 'ပျမ်းမျှအသုံးပြုချိန်',
        'recent_activity': 'မကြာသေးမီက လုပ်ဆောင်မှုများ',
        'user_management': 'အသုံးပြုသူစီမံခန့်ခွဲမှု',
        'system_status': 'စနစ်အခြေအနေ',
        'platform_settings': 'ပလက်ဖောင်းဆက်တင်များ',
        'maintenance_mode': 'ပြုပြင်ထိန်းသိမ်းမှုမုဒ်',
        'allow_registrations': 'စာရင်းသွင်းခွင့်ပြုရန်',
        'demo_mode': 'Demo မုဒ် (၃ ကြိမ်)',
        'google_drive_sync': 'Google Drive ထပ်တူပြုလုပ်ခြင်း',
        'api_server': 'API ဆာဗာ',
        'database': 'ဒေတာဘေ့စ်',
        'ai_service': 'AI ဝန်ဆောင်မှု',
        'storage': 'သိုလှောင်မှု'
    },
    
    'errors': {
        '404_title': 'စာမျက်နှာမတွေ့ပါ',
        '404_message': 'အိုး! သင်ရှာဖွေနေသော စာမျက်နှာကို ရှာမတွေ့ပါ။',
        'back_home': 'ပင်မစာမျက်နှာသို့',
        'go_dashboard': 'ဒက်ရှ်ဘုတ်သို့သွားရန်',
        'search': 'တစ်ခုခုရှာဖွေရန်...'
    }
};
