// Myanmar translations - Complete
window.translations = {
    'common': {
        'welcome': 'ကြိုဆိုပါတယ်',
        'login': 'ဝင်ရောက်ရန်',
        'logout': 'ထွက်ရန်',
        'register': 'စာရင်းသွင်းရန်',
        'dashboard': 'ဒက်ရှ်ဘုတ်',
        'settings': 'ဆက်တင်များ',
        'save': 'သိမ်းရန်',
        'cancel': 'ဖျက်သိမ်းရန်',
        'delete': 'ဖျက်ရန်',
        'edit': 'ပြင်ဆင်ရန်',
        'search': 'ရှာဖွေရန်',
        'loading': 'လုပ်ဆောင်နေသည်...',
        'error': 'အမှား',
        'success': 'အောင်မြင်သည်',
        'confirm': 'အတည်ပြုရန်',
        'back': 'နောက်သို့',
        'next': 'ရှေ့သို့',
        'finish': 'ပြီးဆုံးသည်',
        'submit': 'တင်သွင်းရန်',
        'reset': 'ပြန်လည်သတ်မှတ်ရန်',
        'close': 'ပိတ်ရန်',
        'open': 'ဖွင့်ရန်',
        'yes': 'ဟုတ်သည်',
        'no': 'မဟုတ်ပါ',
        'ok': 'အိုကေ',
        'name': 'အမည်',
        'email': 'အီးမေးလ်',
        'password': 'စကားဝှက်',
        'phone': 'ဖုန်းနံပါတ်',
        'address': 'လိပ်စာ',
        'gender': 'လိင်',
        'male': 'အမျိုးသား',
        'female': 'အမျိုးသမီး',
        'other': 'အခြား',
        'prefer_not': 'ဖော်ပြလိုမှုမရှိ',
        'date': 'ရက်စွဲ',
        'time': 'အချိန်',
        'status': 'အခြေအနေ',
        'active': 'အသက်ဝင်သည်',
        'inactive': 'မလှုပ်ရှားပါ',
        'pending': 'ဆိုင်းငံ့ထားသည်',
        'completed': 'ပြီးဆုံးသည်',
        'failed': 'မအောင်မြင်ပါ',
        'info': 'သတင်းအချက်အလက်',
        'warning': 'သတိပေးချက်',
        'danger': 'အန္တရာယ်',
        'help': 'အကူအညီ',
        'about': 'အကြောင်း',
        'contact': 'ဆက်သွယ်ရန်',
        'privacy': 'ကိုယ်ရေးလုံခြုံမှု',
        'terms': 'အသုံးပြုခြင်းဆိုင်ရာ စည်းမျဉ်းများ',
        'language': 'ဘာသာစကား',
        'theme': 'အပြင်အဆင်',
        'dark': 'အမှောင်',
        'light': 'အလင်း',
        'system': 'စနစ်',
        'notifications': 'အသိပေးချက်များ',
        'sound': 'အသံ',
        'vibration': 'တုန်ခါမှု',
        'version': 'ဗားရှင်း',
        'update': 'မွမ်းမံရန်',
        'check_update': 'မွမ်းမံမှုရှိမရှိ စစ်ဆေးရန်',
        'download': 'ဒေါင်းလုဒ်',
        'upload': 'တင်ရန်',
        'share': 'မျှဝေရန်',
        'copy': 'ကူးယူရန်',
        'paste': 'ကပ်ရန်',
        'cut': 'ဖြတ်ရန်',
        'select_all': 'အားလုံးရွေးရန်',
        'undo': 'မလုပ်တော့ရန်',
        'redo': 'ပြန်လုပ်ရန်',
        'find': 'ရှာဖွေရန်',
        'replace': 'အစားထိုးရန်',
        'goto': 'သွားရန်',
        'line': 'လိုင်း',
        'column': 'ကော်လံ',
        'word': 'စကားလုံး',
        'character': 'အက္ခရာ',
        'zoom_in': 'ချဲ့ရန်',
        'zoom_out': 'ကျဉ်းရန်',
        'fullscreen': 'မျက်နှာပြင်အပြည့်',
        'exit_fullscreen': 'မျက်နှာပြင်အပြည့်မှ ထွက်ရန်'
    },
    
    'auth': {
        'login_title': 'ပြန်လည်ကြိုဆိုပါတယ်',
        'login_subtitle': 'ဆက်လက်ရန် ဝင်ရောက်ပါ',
        'register_title': 'အကောင့်ဖွင့်ရန်',
        'register_subtitle': 'သင်၏ခရီးစဉ်ကို စတင်ပါ',
        'reset_title': 'စကားဝှက်ပြန်လည်သတ်မှတ်ရန်',
        'reset_subtitle': 'သင့်အီးမေးလ်ကို ရိုက်ထည့်ပါ',
        'email_label': 'အီးမေးလ်',
        'password_label': 'စကားဝှက်',
        'confirm_password': 'စကားဝှက်အတည်ပြုရန်',
        'current_password': 'လက်ရှိစကားဝှက်',
        'new_password': 'စကားဝှက်အသစ်',
        'confirm_new_password': 'စကားဝှက်အသစ်အတည်ပြုရန်',
        'forgot_password': 'စကားဝှက်မေ့နေပါသလား?',
        'remember_me': 'မှတ်ထားရန်',
        'no_account': 'အကောင့်မရှိသေးဘူးလား?',
        'has_account': 'အကောင့်ရှိပြီးသားလား?',
        'sign_up': 'စာရင်းသွင်းရန်',
        'sign_in': 'ဝင်ရောက်ရန်',
        'sign_out': 'ထွက်ရန်',
        'reset_password': 'စကားဝှက်ပြန်လည်သတ်မှတ်ရန်',
        'send_reset_link': 'ပြန်လည်သတ်မှတ်ရန်လင့်ခ်ပို့ရန်',
        'reset_link_sent': 'ပြန်လည်သတ်မှတ်ရန်လင့်ခ်ကို သင့်အီးမေးလ်သို့ ပို့လိုက်ပါပြီ',
        'check_email': 'ကျေးဇူးပြု၍ သင့်အီးမေးလ်ကို စစ်ဆေးပါ',
        'password_changed': 'စကားဝှက်ကို အောင်မြင်စွာ ပြောင်းလဲပြီးပါပြီ',
        'password_mismatch': 'စကားဝှက်များ မတူညီပါ',
        'invalid_email': 'ကျေးဇူးပြု၍ မှန်ကန်သော အီးမေးလ်လိပ်စာကို ရိုက်ထည့်ပါ',
        'invalid_password': 'စကားဝှက်သည် အနည်းဆုံး ၆ လုံးရှိရပါမည်',
        'weak_password': 'စကားဝှက် အားနည်းလွန်းသည်',
        'medium_password': 'အလယ်အလတ် စကားဝှက်',
        'strong_password': 'ခိုင်မာသော စကားဝှက်',
        'very_strong': 'အလွန်ခိုင်မာသော စကားဝှက်'
    },
    
    'dashboard': {
        'title': 'ဒက်ရှ်ဘုတ်',
        'welcome_back': 'ပြန်လည်ကြိုဆိုပါတယ် {name}',
        'welcome_guest': 'ဧည့်သည်တော် ကြိုဆိုပါတယ်',
        'subtitle': 'သင်၏ပရောဂျက်များ၏ အခြေအနေ',
        'recent_projects': 'မကြာသေးမီက ပရောဂျက်များ',
        'ai_chat': 'AI ချတ်အကူ',
        'documentation': 'စာရွက်စာတမ်းများ',
        'coder': 'ကုဒ်အယ်ဒီတာ',
        'projects_count': 'သင့်တွင် လက်ရှိလုပ်ဆောင်နေသော ပရောဂျက် {count} ခုရှိသည်',
        'files_count': 'ဖိုင် {count} ခု',
        'lines_count': 'ကုဒ်လိုင်း {count} ခု',
        'last_edited': 'နောက်ဆုံးပြင်ဆင်ခဲ့သည် {time}',
        'created_at': 'ဖန်တီးခဲ့သည် {time}',
        'start_chat': 'ချတ်စတင်ရန်',
        'read_docs': 'စာရွက်စာတမ်းဖတ်ရန်',
        'open_coder': 'ကုဒ်အယ်ဒီတာဖွင့်ရန်',
        'continue_project': 'ယခင်ရပ်ထားသည့်နေရာမှ ဆက်လုပ်ရန်',
        'need_help': 'အကူအညီလိုပါသလား? AI အကူနှင့် ချတ်လုပ်ပါ',
        'learn_more': 'ပလက်ဖောင်းကို ထိရောက်စွာအသုံးပြုနည်း လေ့လာရန်'
    },
    
    'chat': {
        'title': 'AI ချတ်အကူ',
        'new_chat': 'ချတ်အသစ်',
        'type_message': 'စာရိုက်ပါ...',
        'upload_file': 'ဖိုင်တင်ရန်',
        'send': 'ပို့ရန်',
        'thinking': 'AI စဉ်းစားနေသည်...',
        'error': 'တောင်းပန်ပါတယ်။ အမှားတစ်ခုဖြစ်သွားပါတယ်။ ထပ်စမ်းကြည့်ပါ။',
        'history': 'ချတ်မှတ်တမ်း',
        'clear_history': 'မှတ်တမ်းရှင်းရန်',
        'delete_chat': 'ချတ်ဖျက်ရန်',
        'chat_with_ai': 'AI အကူနှင့် ချတ်လုပ်ရန်',
        'file_uploaded': 'ဖိုင်တင်ပြီးပါပြီ: {filename}',
        'code_detected': 'ကုဒ်တွေ့ရှိပါသည်။ ကုဒ်အယ်ဒီတာတွင် ဖွင့်ကြည့်မလား?',
        'open_in_coder': 'ကုဒ်အယ်ဒီတာတွင် ဖွင့်ရန်'
    },
    
    'coder': {
        'title': 'ကုဒ်အယ်ဒီတာ',
        'new_file': 'ဖိုင်အသစ်',
        'new_folder': 'ဖိုလ်ဒါအသစ်',
        'save': 'သိမ်းရန်',
        'save_all': 'အားလုံးသိမ်းရန်',
        'run': 'Run',
        'stop': 'Stop',
        'debug': 'Debug',
        'preview': 'အစမ်းကြည့်ရန်',
        'terminal': 'Terminal',
        'file_explorer': 'ဖိုင်ရှာဖွေရန်',
        'file_name': 'ဖိုင်အမည်',
        'file_type': 'ဖိုင်အမျိုးအစား',
        'create_file': 'ဖိုင်ဖန်တီးရန်',
        'delete_file': 'ဖိုင်ဖျက်ရန်',
        'rename_file': 'ဖိုင်အမည်ပြောင်းရန်',
        'unsaved_changes': 'သိမ်းမထားသော အပြောင်းအလဲများရှိသည်',
        'save_to_drive': 'Drive သို့သိမ်းရန်',
        'load_from_drive': 'Drive မှဖွင့်ရန်',
        'enter_file_name': 'ဖိုင်အမည်ထည့်ပါ (extension အပါအဝင်):',
        'select_language': 'ဘာသာစကားရွေးချယ်ရန်',
        'html': 'HTML',
        'css': 'CSS',
        'javascript': 'JavaScript',
        'python': 'Python',
        'json': 'JSON',
        'markdown': 'Markdown'
    },
    
    'terminal': {
        'title': 'Terminal',
        'new_terminal': 'Terminal အသစ်',
        'close_terminal': 'Terminal ပိတ်ရန်',
        'clear_terminal': 'Terminal ရှင်းရန်',
        'copy': 'ကူးယူရန်',
        'paste': 'ကပ်ရန်',
        'select_all': 'အားလုံးရွေးရန်',
        'find': 'ရှာဖွေရန်',
        'split_terminal': 'Terminal ခွဲရန်',
        'working_directory': 'လက်ရှိလမ်းကြောင်း: {dir}',
        'current_user': 'လက်ရှိအသုံးပြုသူ: {user}',
        'command_not_found': 'Command မတွေ့ပါ: {command}',
        'file_not_found': 'ဖိုင်မတွေ့ပါ: {file}',
        'directory_not_found': 'ဖိုလ်ဒါမတွေ့ပါ: {dir}',
        'welcome_message': 'amkyaw.dev Terminal v2.0.0 မှ ကြိုဆိုပါတယ်',
        'help_message': 'ရရှိနိုင်သော command များကိုကြည့်ရန် \'help\' ကိုရိုက်ပါ'
    },
    
    'docs': {
        'title': 'စာရွက်စာတမ်းများ',
        'search': 'စာရွက်စာတမ်းများရှာဖွေရန်...',
        'categories': 'အမျိုးအစားများ',
        'all': 'အားလုံး',
        'getting_started': 'စတင်အသုံးပြုခြင်း',
        'coder': 'ကုဒ်အယ်ဒီတာ',
        'chat': 'AI ချတ်',
        'terminal': 'Terminal',
        'api': 'API',
        'tutorials': 'သင်ခန်းစာများ',
        'faq': 'မေးလေ့ရှိသောမေးခွန်းများ',
        'examples': 'ကုဒ်နမူနာများ',
        'quick_start': 'အမြန်စတင်ရန်လမ်းညွှန်',
        'copy': 'ကူးယူရန်',
        'copied': 'ကူးယူပြီးပါပြီ'
    },
    
    'about': {
        'title': 'ကျွန်ုပ်တို့အကြောင်း',
        'subtitle': 'AI စွမ်းအားသုံးကိရိယာများဖြင့် developer များကို စွမ်းဆောင်နိုင်စေခြင်း',
        'mission': 'ကျွန်ုပ်တို့၏ ရည်မှန်းချက်',
        'mission_text': 'ဉာဏ်ရည်တုကိရိယာများဖြင့် လူတိုင်းကို ကုဒ်ရေးသားခြင်း လက်လှမ်းမီစေရန်',
        'vision': 'ကျွန်ုပ်တို့၏ မျှော်မှန်းချက်',
        'vision_text': 'လူတိုင်း ၎င်းတို့၏ စိတ်ကူးများကို ကုဒ်ဖြင့် အကောင်အထည်ဖော်နိုင်သော ကမ္ဘာတစ်ခု ဖန်တီးရန်',
        'founder': 'တည်ထောင်သူနှင့် ဦးဆောင် developer',
        'founder_name': 'အောင်သူရိန်',
        'stats_users': 'တက်ကြွသောအသုံးပြုသူများ',
        'stats_projects': 'ဖန်တီးပြီးသော ပရောဂျက်များ',
        'stats_conversations': 'AI စကားပြောဆိုမှုများ',
        'stats_tutorials': 'သင်ခန်းစာများ',
        'features': 'ကျွန်ုပ်တို့ကို ရွေးချယ်ရခြင်း အကြောင်းရင်းများ',
        'feature_ai': 'AI စွမ်းအားသုံး',
        'feature_ai_desc': 'ကုဒ်အကြံပြုချက်များနှင့် အမှားရှာပြင်ခြင်းများ ရယူပါ',
        'feature_cloud': 'Cloud သိုလှောင်မှု',
        'feature_cloud_desc': 'Google Drive ဖြင့် ပရောဂျက်များကို သိမ်းဆည်းပြီး ထပ်တူပြုလုပ်ပါ',
        'feature_multi_lang': 'ဘာသာစုံ',
        'feature_multi_lang_desc': 'ပရိုဂရမ်းမင်း ဘာသာစကား ၂၀ ကျော် ပံ့ပိုးမှု',
        'feature_responsive': 'တုံ့ပြန်မှုရှိသော',
        'feature_responsive_desc': 'စက်ပစ္စည်းအားလုံးတွင် ကောင်းမွန်သောအတွေ့အကြုံ',
        'journey': 'ကျွန်ုပ်တို့၏ခရီးစဉ်',
        'contact': 'ဆက်သွယ်ရန်',
        'email': 'အီးမေးလ်',
        'phone': 'ဖုန်း',
        'address': 'လိပ်စာ',
        'address_details': 'နေပြည်တော်၊ မြန်မာ',
        'copyright': '© {year} amkyaw.dev။ မူပိုင်ခွင့်အားလုံး လက်ဝယ်ရှိသည်။'
    },
    
    'admin': {
        'title': 'အက်မင် panel',
        'subtitle': 'သင်၏ပလက်ဖောင်းနှင့် အသုံးပြုသူများကို စီမံခန့်ခွဲရန်',
        'total_users': 'စုစုပေါင်းအသုံးပြုသူများ',
        'active_users': 'တက်ကြွသောအသုံးပြုသူများ',
        'total_projects': 'စုစုပေါင်းပရောဂျက်များ',
        'total_chats': 'စုစုပေါင်း AI စကားပြောဆိုမှုများ',
        'recent_activity': 'မကြာသေးမီက လုပ်ဆောင်မှုများ',
        'user_management': 'အသုံးပြုသူစီမံခန့်ခွဲမှု',
        'system_status': 'စနစ်အခြေအနေ',
        'platform_settings': 'ပလက်ဖောင်းဆက်တင်များ',
        'maintenance_mode': 'ပြုပြင်ထိန်းသိမ်းမှုမုဒ်',
        'enable_maintenance': 'ပြုပြင်ထိန်းသိမ်းမှုမုဒ် ဖွင့်ရန်',
        'disable_maintenance': 'ပြုပြင်ထိန်းသိမ်းမှုမုဒ် ပိတ်ရန်',
        'backup_now': 'ယခု အရန်ကူးရန်',
        'security_settings': 'လုံခြုံရေး ဆက်တင်များ',
        'email_settings': 'အီးမေးလ် ဆက်တင်များ'
    },
    
    'errors': {
        '404_title': 'စာမျက်နှာမတွေ့ပါ',
        '404_message': 'အိုး! သင်ရှာဖွေနေသော စာမျက်နှာ မရှိပါ။',
        '403_title': 'ဝင်ရောက်ခွင့် မရှိပါ',
        '403_message': 'စာမျက်နှာကို ဝင်ရောက်ခွင့် မရှိပါ။',
        '500_title': 'ဆာဗာအမှား',
        '500_message': 'ဆာဗာတွင် အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်။ နောက်မှ ပြန်လုပ်ကြည့်ပါ။',
        'back_home': 'ပင်မစာမျက်နှာသို့',
        'go_dashboard': 'ဒက်ရှ်ဘုတ်သို့သွားရန်',
        'try_again': 'ထပ်စမ်းကြည့်ရန်',
        'search': 'တစ်ခုခုရှာဖွေရန်...'
    }
};