// Russian translations
window.translations = {
    'common': {
        'welcome': 'Добро пожаловать',
        'login': 'Войти',
        'logout': 'Выйти',
        'register': 'Регистрация',
        'dashboard': 'Панель управления',
        'settings': 'Настройки',
        'save': 'Сохранить',
        'cancel': 'Отмена',
        'delete': 'Удалить',
        'edit': 'Редактировать',
        'search': 'Поиск',
        'loading': 'Загрузка...',
        'error': 'Ошибка',
        'success': 'Успешно',
        'confirm': 'Подтвердить',
        'back': 'Назад',
        'next': 'Далее',
        'finish': 'Завершить',
        'submit': 'Отправить',
        'reset': 'Сбросить',
        'close': 'Закрыть',
        'open': 'Открыть',
        'yes': 'Да',
        'no': 'Нет',
        'ok': 'ОК',
        'name': 'Имя',
        'email': 'Эл. почта',
        'password': 'Пароль',
        'phone': 'Телефон',
        'address': 'Адрес',
        'gender': 'Пол',
        'male': 'Мужской',
        'female': 'Женский',
        'other': 'Другой',
        'prefer_not': 'Предпочитаю не указывать',
        'date': 'Дата',
        'time': 'Время',
        'status': 'Статус',
        'active': 'Активный',
        'inactive': 'Неактивный',
        'pending': 'В ожидании',
        'completed': 'Завершено',
        'failed': 'Ошибка',
        'info': 'Информация',
        'warning': 'Предупреждение',
        'danger': 'Опасно',
        'help': 'Помощь',
        'about': 'О нас',
        'contact': 'Контакты',
        'privacy': 'Политика конфиденциальности',
        'terms': 'Условия использования',
        'language': 'Язык',
        'theme': 'Тема',
        'dark': 'Темная',
        'light': 'Светлая',
        'system': 'Системная',
        'version': 'Версия'
    },
    
    'auth': {
        'login_title': 'С возвращением',
        'login_subtitle': 'Войдите, чтобы продолжить',
        'register_title': 'Создать аккаунт',
        'register_subtitle': 'Начните свое путешествие',
        'reset_title': 'Сброс пароля',
        'reset_subtitle': 'Введите email для сброса пароля',
        'email_label': 'Эл. почта',
        'password_label': 'Пароль',
        'confirm_password': 'Подтвердите пароль',
        'forgot_password': 'Забыли пароль?',
        'remember_me': 'Запомнить меня',
        'no_account': 'Нет аккаунта?',
        'has_account': 'Уже есть аккаунт?',
        'sign_up': 'Зарегистрироваться',
        'sign_in': 'Войти',
        'sign_out': 'Выйти',
        'reset_password': 'Сбросить пароль',
        'send_reset_link': 'Отправить ссылку для сброса',
        'reset_link_sent': 'Ссылка для сброса отправлена на ваш email',
        'password_mismatch': 'Пароли не совпадают',
        'invalid_email': 'Пожалуйста, введите корректный email',
        'invalid_password': 'Пароль должен содержать минимум 6 символов',
        'weak_password': 'Слабый пароль',
        'medium_password': 'Средний пароль',
        'strong_password': 'Надежный пароль',
        'very_strong': 'Очень надежный пароль'
    },
    
    'dashboard': {
        'title': 'Панель управления',
        'welcome_back': 'С возвращением, {name}',
        'welcome_guest': 'Добро пожаловать, Гость',
        'subtitle': 'Статус ваших проектов',
        'recent_projects': 'Недавние проекты',
        'ai_chat': 'AI-помощник',
        'documentation': 'Документация',
        'coder': 'Редактор кода',
        'projects_count': 'У вас {count} активных проектов',
        'files_count': '{count} файлов',
        'lines_count': '{count} строк кода',
        'last_edited': 'Последнее редактирование {time}',
        'created_at': 'Создано {time}',
        'start_chat': 'Начать чат',
        'read_docs': 'Читать документацию',
        'open_coder': 'Открыть редактор кода',
        'continue_project': 'Продолжить',
        'need_help': 'Нужна помощь? Общайтесь с AI-помощником',
        'learn_more': 'Узнать больше'
    },
    
    'chat': {
        'title': 'AI-помощник',
        'new_chat': 'Новый чат',
        'type_message': 'Введите сообщение...',
        'upload_file': 'Загрузить файл',
        'send': 'Отправить',
        'thinking': 'AI думает...',
        'error': 'Извините, произошла ошибка. Пожалуйста, попробуйте снова.',
        'history': 'История чата',
        'clear_history': 'Очистить историю',
        'delete_chat': 'Удалить чат',
        'chat_with_ai': 'Общайтесь с AI-помощником',
        'file_uploaded': 'Файл загружен: {filename}',
        'code_detected': 'Обнаружен код. Открыть в редакторе кода?',
        'open_in_coder': 'Открыть в редакторе кода'
    },
    
    'coder': {
        'title': 'Редактор кода',
        'new_file': 'Новый файл',
        'new_folder': 'Новая папка',
        'save': 'Сохранить',
        'save_all': 'Сохранить все',
        'run': 'Запустить',
        'preview': 'Предпросмотр',
        'terminal': 'Терминал',
        'file_explorer': 'Проводник файлов',
        'file_name': 'Имя файла',
        'file_type': 'Тип файла',
        'create_file': 'Создать файл',
        'delete_file': 'Удалить файл',
        'rename_file': 'Переименовать файл',
        'unsaved_changes': 'Есть несохраненные изменения',
        'save_to_drive': 'Сохранить в Google Диск',
        'load_from_drive': 'Загрузить с Google Диска',
        'enter_file_name': 'Введите имя файла (с расширением):',
        'select_language': 'Выберите язык',
        'html': 'HTML',
        'css': 'CSS',
        'javascript': 'JavaScript',
        'python': 'Python',
        'json': 'JSON',
        'markdown': 'Markdown'
    },
    
    'terminal': {
        'title': 'Терминал',
        'new_terminal': 'Новый терминал',
        'clear_terminal': 'Очистить терминал',
        'copy': 'Копировать',
        'paste': 'Вставить',
        'command_not_found': 'Команда не найдена: {command}',
        'file_not_found': 'Файл не найден: {file}',
        'directory_not_found': 'Директория не найдена: {dir}',
        'welcome_message': 'Добро пожаловать в терминал amkyaw.dev v2.0.0',
        'help_message': 'Введите \'help\' для просмотра доступных команд'
    },
    
    'docs': {
        'title': 'Документация',
        'search': 'Поиск в документации...',
        'categories': 'Категории',
        'all': 'Все',
        'getting_started': 'Начало работы',
        'coder': 'Редактор кода',
        'chat': 'AI-чат',
        'terminal': 'Терминал',
        'api': 'API',
        'tutorials': 'Уроки',
        'faq': 'Часто задаваемые вопросы',
        'examples': 'Примеры кода',
        'quick_start': 'Быстрый старт',
        'copy': 'Копировать',
        'copied': 'Скопировано!'
    },
    
    'about': {
        'title': 'О нас',
        'subtitle': 'Расширение возможностей разработчиков с помощью AI-инструментов',
        'mission': 'Наша миссия',
        'mission_text': 'Сделать программирование доступным для всех с помощью интеллектуальных инструментов и AI-помощи',
        'vision': 'Наше видение',
        'vision_text': 'Создать мир, где каждый может воплотить свои идеи в коде',
        'founder': 'Основатель и ведущий разработчик',
        'founder_name': 'Аунг Тху Рейн',
        'stats_users': 'Активных пользователей',
        'stats_projects': 'Создано проектов',
        'stats_conversations': 'AI-диалогов',
        'stats_tutorials': 'Уроков',
        'features': 'Почему выбирают нас',
        'feature_ai': 'На базе AI',
        'feature_ai_desc': 'Получайте интеллектуальные предложения кода и помощь в отладке',
        'feature_cloud': 'Облачное хранилище',
        'feature_cloud_desc': 'Сохраняйте и синхронизируйте проекты с Google Диском',
        'feature_multi_lang': 'Мультиязычность',
        'feature_multi_lang_desc': 'Поддержка более 20 языков программирования',
        'feature_responsive': 'Адаптивный дизайн',
        'feature_responsive_desc': 'Идеальный опыт на всех устройствах',
        'contact': 'Свяжитесь с нами',
        'email': 'Эл. почта',
        'phone': 'Телефон',
        'address': 'Адрес',
        'address_details': 'Нейпьидо, Мьянма',
        'copyright': '© {year} amkyaw.dev. Все права защищены.'
    },
    
    'admin': {
        'title': 'Панель администратора',
        'subtitle': 'Управление платформой и пользователями',
        'total_users': 'Всего пользователей',
        'active_users': 'Активных пользователей',
        'total_projects': 'Всего проектов',
        'total_chats': 'Всего AI-диалогов',
        'recent_activity': 'Недавняя активность',
        'user_management': 'Управление пользователями',
        'system_status': 'Состояние системы',
        'platform_settings': 'Настройки платформы'
    },
    
    'errors': {
        '404_title': 'Страница не найдена',
        '404_message': 'Извините! Страница, которую вы ищете, не существует',
        '403_title': 'Доступ запрещен',
        '403_message': 'У вас нет прав для доступа к этой странице',
        '500_title': 'Ошибка сервера',
        '500_message': 'Произошла ошибка на сервере. Пожалуйста, попробуйте позже.',
        'back_home': 'Вернуться на главную',
        'go_dashboard': 'Перейти к панели управления',
        'try_again': 'Попробовать снова',
        'search': 'Поиск...'
    }
};