// Thai translations
window.translations = {
    'common': {
        'welcome': 'ยินดีต้อนรับ',
        'login': 'เข้าสู่ระบบ',
        'logout': 'ออกจากระบบ',
        'register': 'ลงทะเบียน',
        'dashboard': 'แดชบอร์ด',
        'settings': 'การตั้งค่า',
        'save': 'บันทึก',
        'cancel': 'ยกเลิก',
        'delete': 'ลบ',
        'edit': 'แก้ไข',
        'search': 'ค้นหา',
        'loading': 'กำลังโหลด...',
        'error': 'ข้อผิดพลาด',
        'success': 'สำเร็จ',
        'confirm': 'ยืนยัน',
        'back': 'กลับ',
        'next': 'ถัดไป',
        'finish': 'เสร็จสิ้น',
        'submit': 'ส่ง',
        'reset': 'รีเซ็ต',
        'close': 'ปิด',
        'open': 'เปิด',
        'yes': 'ใช่',
        'no': 'ไม่',
        'ok': 'ตกลง',
        'name': 'ชื่อ',
        'email': 'อีเมล',
        'password': 'รหัสผ่าน',
        'phone': 'โทรศัพท์',
        'address': 'ที่อยู่',
        'gender': 'เพศ',
        'male': 'ชาย',
        'female': 'หญิง',
        'other': 'อื่นๆ',
        'prefer_not': 'ไม่ระบุ',
        'date': 'วันที่',
        'time': 'เวลา',
        'status': 'สถานะ',
        'active': 'ใช้งาน',
        'inactive': 'ไม่ใช้งาน',
        'pending': 'รอดำเนินการ',
        'completed': 'เสร็จสมบูรณ์',
        'failed': 'ล้มเหลว',
        'info': 'ข้อมูล',
        'warning': 'คำเตือน',
        'danger': 'อันตราย',
        'help': 'ช่วยเหลือ',
        'about': 'เกี่ยวกับ',
        'contact': 'ติดต่อ',
        'privacy': 'นโยบายความเป็นส่วนตัว',
        'terms': 'ข้อกำหนดการให้บริการ',
        'language': 'ภาษา',
        'theme': 'ธีม',
        'dark': 'มืด',
        'light': 'สว่าง',
        'system': 'ตามระบบ',
        'version': 'เวอร์ชัน'
    },
    
    'auth': {
        'login_title': 'ยินดีต้อนรับกลับ',
        'login_subtitle': 'เข้าสู่ระบบเพื่อดำเนินการต่อ',
        'register_title': 'สร้างบัญชี',
        'register_subtitle': 'เริ่มต้นการเดินทางของคุณ',
        'reset_title': 'รีเซ็ตรหัสผ่าน',
        'reset_subtitle': 'ใส่อีเมลของคุณเพื่อรีเซ็ตรหัสผ่าน',
        'email_label': 'อีเมล',
        'password_label': 'รหัสผ่าน',
        'confirm_password': 'ยืนยันรหัสผ่าน',
        'forgot_password': 'ลืมรหัสผ่าน?',
        'remember_me': 'จดจำฉัน',
        'no_account': 'ยังไม่มีบัญชี?',
        'has_account': 'มีบัญชีอยู่แล้ว?',
        'sign_up': 'ลงทะเบียน',
        'sign_in': 'เข้าสู่ระบบ',
        'sign_out': 'ออกจากระบบ',
        'reset_password': 'รีเซ็ตรหัสผ่าน',
        'send_reset_link': 'ส่งลิงก์รีเซ็ต',
        'reset_link_sent': 'ลิงก์รีเซ็ตถูกส่งไปยังอีเมลของคุณแล้ว',
        'password_mismatch': 'รหัสผ่านไม่ตรงกัน',
        'invalid_email': 'กรุณาใส่อีเมลที่ถูกต้อง',
        'invalid_password': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
        'weak_password': 'รหัสผ่านอ่อนเกินไป',
        'medium_password': 'รหัสผ่านปานกลาง',
        'strong_password': 'รหัสผ่านแข็งแรง',
        'very_strong': 'รหัสผ่านแข็งแรงมาก'
    },
    
    'dashboard': {
        'title': 'แดชบอร์ด',
        'welcome_back': 'ยินดีต้อนรับกลับ {name}',
        'welcome_guest': 'ยินดีต้อนรับผู้เยี่ยมชม',
        'subtitle': 'สถานะโปรเจกต์ของคุณ',
        'recent_projects': 'โปรเจกต์ล่าสุด',
        'ai_chat': 'ผู้ช่วยแชท AI',
        'documentation': 'เอกสาร',
        'coder': 'โปรแกรมแก้ไขโค้ด',
        'projects_count': 'คุณมีโปรเจกต์ที่กำลังดำเนินการ {count} โปรเจกต์',
        'files_count': '{count} ไฟล์',
        'lines_count': '{count} บรรทัดโค้ด',
        'last_edited': 'แก้ไขล่าสุด {time}',
        'created_at': 'สร้างเมื่อ {time}',
        'start_chat': 'เริ่มแชท',
        'read_docs': 'อ่านเอกสาร',
        'open_coder': 'เปิดโปรแกรมแก้ไขโค้ด',
        'continue_project': 'ดำเนินการต่อ',
        'need_help': 'ต้องการความช่วยเหลือ? แชทกับผู้ช่วย AI',
        'learn_more': 'เรียนรู้เพิ่มเติม'
    },
    
    'chat': {
        'title': 'ผู้ช่วยแชท AI',
        'new_chat': 'แชทใหม่',
        'type_message': 'พิมพ์ข้อความ...',
        'upload_file': 'อัปโหลดไฟล์',
        'send': 'ส่ง',
        'thinking': 'AI กำลังคิด...',
        'error': 'ขออภัย เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
        'history': 'ประวัติการแชท',
        'clear_history': 'ล้างประวัติ',
        'delete_chat': 'ลบแชท',
        'chat_with_ai': 'แชทกับผู้ช่วย AI',
        'file_uploaded': 'อัปโหลดไฟล์: {filename}',
        'code_detected': 'ตรวจพบโค้ด ต้องการเปิดในโปรแกรมแก้ไขโค้ดหรือไม่?',
        'open_in_coder': 'เปิดในโปรแกรมแก้ไขโค้ด'
    },
    
    'coder': {
        'title': 'โปรแกรมแก้ไขโค้ด',
        'new_file': 'ไฟล์ใหม่',
        'new_folder': 'โฟลเดอร์ใหม่',
        'save': 'บันทึก',
        'save_all': 'บันทึกทั้งหมด',
        'run': 'รัน',
        'preview': 'ตัวอย่าง',
        'terminal': 'เทอร์มินัล',
        'file_explorer': 'ตัวสำรวจไฟล์',
        'file_name': 'ชื่อไฟล์',
        'file_type': 'ประเภทไฟล์',
        'create_file': 'สร้างไฟล์',
        'delete_file': 'ลบไฟล์',
        'rename_file': 'เปลี่ยนชื่อไฟล์',
        'unsaved_changes': 'มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก',
        'save_to_drive': 'บันทึกลง Google Drive',
        'load_from_drive': 'โหลดจาก Google Drive',
        'enter_file_name': 'ใส่ชื่อไฟล์ (พร้อมนามสกุล):',
        'select_language': 'เลือกภาษา',
        'html': 'HTML',
        'css': 'CSS',
        'javascript': 'JavaScript',
        'python': 'Python',
        'json': 'JSON',
        'markdown': 'Markdown'
    },
    
    'terminal': {
        'title': 'เทอร์มินัล',
        'new_terminal': 'เทอร์มินัลใหม่',
        'clear_terminal': 'ล้างเทอร์มินัล',
        'copy': 'คัดลอก',
        'paste': 'วาง',
        'command_not_found': 'ไม่พบคำสั่ง: {command}',
        'file_not_found': 'ไม่พบไฟล์: {file}',
        'directory_not_found': 'ไม่พบไดเรกทอรี: {dir}',
        'welcome_message': 'ยินดีต้อนรับสู่ amkyaw.dev Terminal v2.0.0',
        'help_message': 'พิมพ์ \'help\' เพื่อดูคำสั่งที่ใช้งานได้'
    },
    
    'docs': {
        'title': 'เอกสาร',
        'search': 'ค้นหาเอกสาร...',
        'categories': 'หมวดหมู่',
        'all': 'ทั้งหมด',
        'getting_started': 'เริ่มต้นใช้งาน',
        'coder': 'โปรแกรมแก้ไขโค้ด',
        'chat': 'แชท AI',
        'terminal': 'เทอร์มินัล',
        'api': 'API',
        'tutorials': 'บทเรียน',
        'faq': 'คำถามที่พบบ่อย',
        'examples': 'ตัวอย่างโค้ด',
        'quick_start': 'คู่มือเริ่มต้นใช้งานด่วน',
        'copy': 'คัดลอก',
        'copied': 'คัดลอกแล้ว!'
    },
    
    'about': {
        'title': 'เกี่ยวกับเรา',
        'subtitle': 'เสริมศักยภาพนักพัฒนาด้วยเครื่องมือที่ขับเคลื่อนด้วย AI',
        'mission': 'พันธกิจของเรา',
        'mission_text': 'ทำให้การเขียนโค้ดเข้าถึงได้สำหรับทุกคนผ่านเครื่องมืออัจฉริยะและความช่วยเหลือจาก AI',
        'vision': 'วิสัยทัศน์ของเรา',
        'vision_text': 'สร้างโลกที่ทุกคนสามารถทำให้ความคิดของตนเป็นจริงผ่านโค้ด',
        'founder': 'ผู้ก่อตั้งและนักพัฒนาหลัก',
        'founder_name': 'อ่อง ทู เรน',
        'stats_users': 'ผู้ใช้ที่ใช้งาน',
        'stats_projects': 'โปรเจกต์ที่สร้าง',
        'stats_conversations': 'การสนทนากับ AI',
        'stats_tutorials': 'บทเรียน',
        'features': 'ทำไมเลือกเรา',
        'feature_ai': 'ขับเคลื่อนด้วย AI',
        'feature_ai_desc': 'รับคำแนะนำโค้ดและความช่วยเหลือในการดีบัก',
        'feature_cloud': 'พื้นที่จัดเก็บคลาวด์',
        'feature_cloud_desc': 'บันทึกและซิงค์โปรเจกต์กับ Google Drive',
        'feature_multi_lang': 'หลายภาษา',
        'feature_multi_lang_desc': 'รองรับภาษาโปรแกรมมากกว่า 20 ภาษา',
        'feature_responsive': 'ตอบสนองทุกอุปกรณ์',
        'feature_responsive_desc': 'ประสบการณ์ที่สมบูรณ์แบบบนทุกอุปกรณ์',
        'contact': 'ติดต่อเรา',
        'email': 'อีเมล',
        'phone': 'โทรศัพท์',
        'address': 'ที่อยู่',
        'address_details': 'เนปิดอว์, เมียนมาร์',
        'copyright': '© {year} amkyaw.dev สงวนลิขสิทธิ์'
    },
    
    'admin': {
        'title': 'แผงผู้ดูแลระบบ',
        'subtitle': 'จัดการแพลตฟอร์มและผู้ใช้ของคุณ',
        'total_users': 'ผู้ใช้ทั้งหมด',
        'active_users': 'ผู้ใช้ที่ใช้งาน',
        'total_projects': 'โปรเจกต์ทั้งหมด',
        'total_chats': 'การสนทนากับ AI ทั้งหมด',
        'recent_activity': 'กิจกรรมล่าสุด',
        'user_management': 'การจัดการผู้ใช้',
        'system_status': 'สถานะระบบ',
        'platform_settings': 'การตั้งค่าแพลตฟอร์ม'
    },
    
    'errors': {
        '404_title': 'ไม่พบหน้า',
        '404_message': 'ขออภัย! ไม่พบหน้าที่คุณกำลังค้นหา',
        '403_title': 'การเข้าถึงถูกปฏิเสธ',
        '403_message': 'คุณไม่มีสิทธิ์เข้าถึงหน้านี้',
        '500_title': 'ข้อผิดพลาดของเซิร์ฟเวอร์',
        '500_message': 'เกิดข้อผิดพลาดบนเซิร์ฟเวอร์ กรุณาลองใหม่อีกครั้ง',
        'back_home': 'กลับหน้าหลัก',
        'go_dashboard': 'ไปที่แดชบอร์ด',
        'try_again': 'ลองอีกครั้ง',
        'search': 'ค้นหา...'
    }
};